import Head from 'next/head'
import Image from 'next/image'
import Pokedex from 'pokedex-promise-v2'
import { useState, useEffect, useRef } from 'react'
import PokeCard from '../components/main/PokeCard';
import LoadingTop from '../components/main/LoadingTop'
import RegionTab from '../components/main/RegionTab';

const Poke = new Pokedex()

export default function Home() {
  const limitPokemon = 48
  let lastPokemonEntry = useRef(0)

  const [pageState, setpageState] = useState({
    loading: {
      pokedexList: 1,
      pokedexSelected: 0,
      pokemonList: 0
    },
    show: {
      loadmore: 1
    },
    pokedex: {
      list: [],
      selected: null
    },
    pokemonList: [],
    pokemonMaxEntry: 0,
    pokemonDisplay: []
  });

  const updateState = (newState) => {
    setpageState(prev => {
      return {
        ...prev,
        ...newState
      }
    })
  }

  const getPokedexList = () => {
    updateState({
      loading: {
        ...pageState.loading,
        pokedexList: 1
      }
    })
    Poke.getPokedexList()
    .catch(e => {
      console.error('getPokedexList', e)
    })
    .then(resp => {
      updateState({
        loading: {
          ...pageState.loading,
          pokedexList: 0
        },
        pokedex: {
          list: resp.results,
          selected: resp.results[0].name
        }
      })

      return resp
    })
  }

  const getPokemonDisplay = (pokemonList=[]) => {
    if(pageState.loading.pokemonList) {
      alert('Loading. Please Wait...')
      return false
    } // endif

    const nextLast = lastPokemonEntry.current + limitPokemon
    let catchEntry = pokemonList.filter(entry => {
      return entry.entry_number > lastPokemonEntry.current && entry.entry_number <= nextLast
    })

    let pokemonDisplay = catchEntry
    if(lastPokemonEntry.current > 0) {
      pokemonDisplay = [
        ...pageState.pokemonDisplay,
        ...pokemonDisplay
      ]
    } // endif
    console.log({pokemonDisplay, catchEntry, lastPokemonEntry, pokemonList})
    lastPokemonEntry.current = nextLast

    return pokemonDisplay
  }

  const loadPokemonDisplay = () => {
    let pokemonDisplay = getPokemonDisplay(pageState.pokemonList)
    console.log('loadPokemonDisplay', {limitPokemon, lastPokemonEntry, pageState})
    updateState({
      show: {
        ...pageState.show,
        loadmore: lastPokemonEntry.current < pageState.pokemonMaxEntry
      },
      pokemonDisplay
    })
  }

  const getPokedexDetail = async (name) => {
    updateState({
      loading: {
        ...pageState.loading,
        pokedexSelected: 1
      }
    })
    Poke.getPokedexByName(name).then(resp => {
      lastPokemonEntry.current = 0
      const pokemonDisplay = getPokemonDisplay(resp.pokemon_entries)
      const entryOnly = resp.pokemon_entries.map(entry => entry.entry_number)
      const pokemonMaxEntry = Math.max(...entryOnly)

      updateState({
        loading: {
          ...pageState.loading,
          pokedexSelected: 0
        },
        show: {
          ...pageState.show,
          loadmore: limitPokemon < pokemonMaxEntry
        },
        pokemonList: resp.pokemon_entries,
        pokemonDisplay: pokemonDisplay,
        pokemonMaxEntry
      })
    })
  }

  useEffect(() => {
    if(pageState.pokedex.selected) {
      getPokedexDetail(pageState.pokedex.selected)
    } // endif

  }, [pageState.pokedex.selected]);

  useEffect(() => {
    getPokedexList()
  }, []);

  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-screen text-gray-900'>
        <LoadingTop hidden={![pageState.loading.pokedexList, pageState.loading.pokemonList, pageState.loading.pokedexSelected].includes(1)} />
        <div className='fixed z-20 top-0 left-1/2 -translate-x-1/2 w-full bg-gray-50 container mx-auto'>
          <div className='my-4 font-semibold text-xl'>Region Select</div>
          <div className="w-full flex gap-4 pb-6 overflow-x-scroll">
            {
              pageState.pokedex.list.map(region => (
                <RegionTab
                  onClick={() => updateState({
                    pokedex: {
                      ...pageState.pokedex,
                      selected: region.name
                    }
                  })}
                  title={region.name} key={region.url}
                  isActive={region.name == pageState.pokedex.selected}
                  />
              ))
            }
          </div>
        </div>
        <div className='container mx-auto pb-10 px-4 md:px-0'>
          <h3 className='mt-36 text-3xl text-center'>Pokedex</h3>

          <div className='my-6 font-semibold'>Found {pageState.pokemonList.length} Pokemons</div>
          <div className='grid grid-cols-2 lg:grid-cols-6 gap-4 md:px-0'>
            {
              pageState.pokemonDisplay.map(entry =>
                (
                  <PokeCard key={entry.entry_number}
                    pokedexNumber={entry.entry_number}
                    url={entry?.pokemon_species?.url}
                    pokemonName={entry?.pokemon_species?.name}
                    />
                )
              )
            }
          </div>

          {
            pageState.show.loadmore ?
            <div className='flex justify-center my-8'>
              <button type='button'
                onClick={loadPokemonDisplay}
                className='btn btn-primary'>
                Load More
              </button>
            </div>
            :
            <div className="my-8 w-full border-t border-white relative">
              <div className='absolute text-center left-1/2 top-0 -translate-x-1/2 -mt-3 bg-slate-800 w-48'>
                End of Page
              </div>
            </div>
          }
        </div>
      </main>
    </div>
  )
}
